### ISSUE TITLE
Node Tasks - Liveliness, Minipool Statuses, Fee Signal

### ISSUE THREAD

**Issue by darcius** [rocket-pool/rocketpool#104]
In RP1, nodes were required to checkin with the smart contracts every 15mins, but due to transaction fees, this may or may not be possible on chain if scaling hasn't been implemented at the same time as Casper in Eth2.0. 

In RP1, the checkin did three main things:
- Reported the nodes server load
- Recorded its last checkin time + disabled nodes that had not checked in `getSmartNodeSetInactiveDuration()` duration 
- Updated the status of any minipool (launched, withdrew etc).

In RP2, as the Casper system is now part of the beacon chain (not a contract) so we will need to approach this a bit differently. Checkins should now be once every 24hrs (this can be increased with scaling/fees coming down) and it should:
- [x] Report the nodes current server load and record it (individual task)
- [x] Disabled nodes that had not checked in `getSmartNodeSetInactiveDuration()` duration (individual task), note that `node.active` will need to be checked when chunks are assigned. 
- [x] Minipool statuses will now need to be reported from the smart node daemon as they are part of the beacon chain. We'll need to figure out a good approach for this, as since the smart contracts can't directly query Casper anymore, the node will need to provide it's minipools with their status and they update accordingly.
- [x] When a node checks in, it will report its current fee vote as a percentage in Wei (eg 0.02 ether = 2 %). This will need to be recorded (only if its changed from the previous fee signal) and the system should calculate once every 24hrs the median fee signal from all nodes. This will also need to be recorded in minipools when they launch, so it doesn't effect any currently deployed ones. We'll need to add limits on how much it is allowed to change from a previous signal too, perhaps in the settings. Eg. If a node votes 0.05 fee one day, it can't lurch all the way to 0.5 the next.

Open to suggestions on network fee signalling in general, will most likely need to be refined.

**Comment by moles1** [comment]
A few notes on the above:

- I don't think writing individual tasks for recording the node's server load (or other minor details) is a good fit, for a couple of reasons. Firstly, the overhead of instantiating a task contract and calling its run method is higher than just the one-liner required to write to storage. Secondly, the information needs to be passed in somehow, whereas the tasks don't accept any parameters, they just perform jobs with known information... not sure what this would look like if we had to rework them to accept arbitrary params, and how this data would be passed in. For now, I've just recorded the node's server load directly in the `RocketNodeAPI.checkin` method (along with node fee vote and last checkin time).

- I've used a "checkin queue" to implement the logic which disables inactive nodes. When a node is first created, it gets added to the end of the queue. When a node checks in and the `DisableInactiveNodes` task is run, we check the first 3 items in the queue (there is a setting for this which can be changed but 3 feels good imo). For each item, we set it to inactive if it hasn't checked in in the inactive duration. Then, we remove it from the front of the queue and add it back to the end. This way, each checkin only does a few loops and we don't blow out gas costs. The nodes never leave the queue, they just get put back on the end after being checked, and we cycle around to them again later. Doing 3 items per checkin means we move through the queue pretty quickly and should get the correct behaviour even if a lot of nodes have problems and fail to check in.

- After trying a few different failed approaches, I'm not sure that finding the median vote is viable for calculating the dynamic node operator fee. The problem with finding the median is that we need to maintain the whole set of votes for the 24 hour period _in order_, which gets computationally expensive very quickly and would blow out gas costs. E.g. if we have 200 votes and someone submits a new lowest vote, that needs to go to the start of the list - which means shuffling all 200 existing items up.

I played around with some methods to use the _mean_ instead, which work fine technically, but I'm not sure how useful that is in practice. If operators feel really strongly that the price needs to change, they will submit votes for either 100% or 0%. Other operators would need to vote the other way to counteract this (rather than submitting votes for the actual target number they want), and the whole thing basically becomes binary very quickly.

Considering that we also want to limit the amount that the fee can swing by in a given period, maybe the best approach is to keep it simple and hard-code the swing amount in a setting (e.g. 1% per period), and just provide 3 options to vote on: increase the fee, decrease the fee, or leave it the same. Whichever option gets more votes in the period determines the new fee. This should feel familiar to people already since it's basically how the ethereum gas block limit voting works.

Final thought - it would probably also be good to weight votes by the amount of RPL the node currently has assigned to minipools. This would mean that random people couldn't just create a bunch of empty node contracts and use them to submit heaps of votes and game the system.

**Comment by moles1** [comment]
Re: minipool statuses:

- Statuses 0, 1, 2, 5 and 6 (Initialised, Pre-Launch, Staking, Closed and Timed Out) are set by mainchain events

- Statuses 3 and 4 (Logged Out and Withdrawn) are set by beacon chain events

The current solution for statuses 3 and 4 is to set them using a RP-controlled script with network owner privileges. This script will consume beacon chain events and update the validators' associated minipools appropriately.
