### ISSUE TITLE
new rocketPool javascript

### ISSUE THREAD

**Issue by DamboRam** [rocket-pool/rocketpool#153]
Error: Uncaught (in promise): TypeError: Cannot read property '77' of undefined when creating const rp = new RocketPool(this.web3, "RocketStorage.json");
77 is the chain id of my custom rpc Metamask account and it is connect to http://gateway.rocketpool.net:8888

**Comment by DamboRam** [comment]
77 is the chain id of my custom rpc Metamask account
and it is connect to http://gateway.rocketpool.net:8888

**Comment by moles1** [comment]
Hi @DamboRam ! Please raise any issues related to the JS library under that repo, at: https://github.com/rocket-pool/rocketpool-js

The second argument to the RocketPool constructor needs to be the actual Truffle contract artifact for RocketStorage as a javascript object, not a string. The artifact file for the beta test network is attached: [RocketStorage.json.zip](https://github.com/rocket-pool/rocketpool/files/3727321/RocketStorage.json.zip)

You can load the artifact file directly with an `import` statement if ES6 import syntax is available in your JS environment:

```
import RocketStorage from '/path/to/RocketStorage.json';
```

Otherwise, if you're using nodejs, you can load it using the `fs` module:

```
const fs = require('fs');
...
const RocketStorage = JSON.parse(fs.readFileSync('/path/to/RocketStorage.json'));
```

Then, simply pass it as the second argument to the RP constructor:

```
const rp = new RocketPool(this.web3, RocketStorage);
```

Thanks :)
Jake
