### ISSUE TITLE
Enhancement: "Advanced" eth1 option, Bring Your Own URL

### ISSUE THREAD

**Issue by yorickdowne** [rocket-pool/rocketpool#181]
It'd be great to have an "Advanced" option for eth1 during config, that allows someone to BYOU, Bring Your Own URL.

This would enable use cases such as:
- User-supplied eth1 node, possibly because they are running rpool alongside solo staking or otherwise have an eth1 node already available
- 3rd-party eth1 node other than infura

**Comment by moles1** [comment]
This currently won't work for running a separate eth1 client on the host OS because the eth1 proxy runs inside a docker container and won't be able to resolve 127.0.0.1 to the host OS. We'll find another way to enable this which might involve some documentation and manual config on the part of the user.

Nevertheless, this is still a good option for external eth1 providers which the proxy container *can* resolve. I've raised an issue on the smartnode-install repo for this here :) https://github.com/rocket-pool/smartnode-install/issues/14
