### ISSUE TITLE
Customized Grafana config file reverted to default Grafana config file when I upgraded to RC8

### ISSUE THREAD

**Issue by gpetru1** [rocket-pool/rocketpool#225]
My email server and SSL configuration reverted after upgrade.

**Comment by jclapis** [comment]
That is an expected result of doing `rocketpool service terminate`, which deletes all of the Docker container data. This removes the eth1 and eth2 chain data (which you needed to do in order to switch from Prater to mainnet), but it also removes the Prometheus database to get rid of any cached information from the previous network. Grafana's database is unfortunately included in this removal as a side-effect.

Luckily, you should only need to run `rocketpool service terminate` this one time as you change networks, so it won't happen again during later updates.
